# Стадия 1: build
FROM node:20-alpine as build

WORKDIR /app

# Установить зависимости
COPY package*.json ./
RUN npm install

# Скопировать исходники
COPY . .

# Сборка (production)
RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/.output ./.output
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3000

# Запуск Nuxt в продакшн-режиме
CMD ["node", ".output/server/index.mjs"]